### ISSUE TITLE
Need to create new release

### ISSUE THREAD

**Issue by AndriyGo** [Jerrrr/SwiftyStarRatingView#6]
Currently SwiftyStarRatingView is not available through Carthage because it is able to pull only the latest release from Feb 21. Please create a new release in order to tag most recent commits and make framework available in Carthage.

Thanks in advance!

**Comment by Jerrrr** [comment]
I am very busy recently, I will solve the problem later, thanks for your proposal.

Thanks!

**Comment by rnkyr** [comment]
Any news here?

**Comment by Jerrrr** [comment]
Release 1.1.0 have published, if anything trouble you, please open another iussue or open this issue again.
